/**
 * Sound playback via Howler.js using the WAV assets generated by
 * scripts/generate-sounds.mjs (they live in /public/sounds). Howler is
 * imported lazily so this module is safe to use in server-rendered pages too.
 */

export type SoundName = "tap" | "correct" | "wrong" | "complete";

const MUTE_KEY = "questly-muted";

export function isMuted(): boolean {
  if (typeof window === "undefined") return false;
  return localStorage.getItem(MUTE_KEY) === "1";
}

export function setMuted(muted: boolean): void {
  localStorage.setItem(MUTE_KEY, muted ? "1" : "0");
}

type HowlLike = { play: () => number };

const VOLUMES: Record<SoundName, number> = {
  tap: 0.5,
  correct: 0.85,
  wrong: 0.7,
  complete: 0.9,
};

const cache: Partial<Record<SoundName, HowlLike>> = {};
let priming: Promise<void> | null = null;

/** Preloads the audio files — call once from a useEffect. */
export function primeSounds(): Promise<void> {
  if (typeof window === "undefined") return Promise.resolve();
  if (!priming) {
    priming = (async () => {
      try {
        const { Howl } = await import("howler");
        (Object.keys(VOLUMES) as SoundName[]).forEach((name) => {
          cache[name] = new Howl({
            src: [`/sounds/${name}.wav`],
            volume: VOLUMES[name],
            preload: true,
          });
        });
      } catch {
        // Audio is a nice-to-have; never let it break the app.
      }
    })();
  }
  return priming;
}

export function playSound(name: SoundName): void {
  if (isMuted()) return;
  void primeSounds().then(() => cache[name]?.play());
}
